insert into Genre values (2001,'Проза');
insert into Genre values (2002,'Детектив');
insert into Genre values (2003,'Фэнтези');
insert into Genre values (2004,'Роман');
insert into Genre values (2005,'Поэзия');
insert into Genre values (2006,'Комиксы');
insert into Genre values (2007,'Детская литература');
insert into Genre values (2008,'Ужасы');
insert into Genre values (2009,'Биография');
insert into Genre values (2010,'Психология');
