version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      mynet:
        ipv4_address: 192.168.15.2

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      mynet:
        ipv4_address: 192.168.15.4

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.15.0/24

